sudo: required
language: python
services:
  - docker
before_install:
  - docker build -t dendory02/simpleflask .
  - docker run -d -p 8080:8080 --name app dendory02/simpleflask
  - docker ps -a
script:
  - curl -k http://localhost:8080/
after_script:
  - docker rm -f app
